tournament :
	java main.TournamentMain
league :
	java main.LeagueMain

jarLeague :
	jar cvfm ../league.jar ../manifest-league.txt *

jarTournament :
	jar cvfm ../tournament.jar ../manifest-tournament.txt *